export const featured = [{
    id: 0,
    title: "The Son Got Up",
    content: "Church Online for March 31, 2024",
    date: "March 31, 2024",
    mediaID: "357301587296288",
    type: "video"
},
{
    id: 1,
    title: "Built Before The Storm",
    content: "Church Online for March 10, 2024",
    date: "March 17, 2024",
    mediaID: "434748875745079",
    type: "video"
},
{
    id: 2,
    title: "Online Worship Service | January 16",
    content: "Church Online for January 16, 2022",
    date: "January 16, 2022",
    mediaID: "3061519324103214",
    type: "video"
},]

export const events = [{
    id: 0,
    title: "From Manger to Majesty",
    content: "Hope of Glory Christian Church Christmas Party 2024. ",
    date: "December 15, 2024",
    mediaID: "christmas",
    type: "photo"
},
{
    id: 1,
    title: "Pista sa Nayon",
    content: "28th Aniversay of Hope of Glory Christian Church",
    date: "November 24, 2024",
    mediaID: "9496140637066830",
    type: "video"
},
{
    id: 2,
    title: "Set Apart & Chosen",
    content: "27th Aniversay of Hope of Glory Christian Church.  A day to rediscover your calling.",
    date: "November 26, 2023",
    mediaID: "341440915275838",
    type: "video"
},
{
    id: 3,
    title: "Christians Engaged | Day 02",
    content: "Christians Engaged Day 2 live streaming.",
    date: "April 12, 2022",
    mediaID: "450797956803300",
    type: "video"
}
]

export const books = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ];
