export const schedule = [{
    id: "sched-1",
    image: "sunday.jpg",
    title: "Sunday Service",
    content: "Let us come together for a time of worship, connection and inspiration. Discover a place where you belong and let’s grow together in faith and God’s love.",
    time:"Every Sunday at 9:00 AM"
},
{
    id: "sched-2",
    image: "prayer.jpg",
    title: "Prayer Meeting",
    content: "Join us for a powerful time of prayer as we seek God’s guidance and peace. Whether you’re carrying a heavy burden or celebrating a victory, let’s come together to lift our hearts in prayer.",
    time:"Every Wednesday at 6:30 PM"
},
{
    id: "sched-3",
    image: "kids.png",
    title: "Kids Church",
    content: "Bring your kids to an exciting, fun-filled adventure at Kids Church! They’ll enjoy engaging activities, uplifting music, and age-appropriate lessons about God’s love.",
    time:"Every Sunday at 10:00 AM"
}]

export const featured = [{
    id: 0,
    title: "The Son Got Up",
    content: "Church Online for March 31, 2024",
    date: "March 31, 2024",
    mediaID: "357301587296288",
    type: "video"
},
{
    id: 1,
    title: "Built Before The Storm",
    content: "Church Online for March 10, 2024",
    date: "March 17, 2024",
    mediaID: "434748875745079",
    type: "video"
},
{
    id: 2,
    title: "Online Worship Service | January 16",
    content: "Church Online for January 16, 2022",
    date: "January 16, 2022",
    mediaID: "3061519324103214",
    type: "video"
},]

export const events = [{
    id: 0,
    title: "From Manger to Majesty",
    content: "Hope of Glory Christian Church Christmas Party 2024. ",
    date: "December 15, 2024",
    mediaID: "christmas",
    type: "photo"
},
{
    id: 1,
    title: "Pista sa Nayon",
    content: "28th Aniversay of Hope of Glory Christian Church",
    date: "November 24, 2024",
    mediaID: "9496140637066830",
    type: "video"
},
{
    id: 2,
    title: "One Way | Daily Vacation Bible School 2024",
    content: "Join us for DVBS 2024 with the exciting theme: One Way | John 14:6",
    date: "July 9-12, 2024",
    mediaID: "one_way",
    type: "photo"
},
{
    id: 3,
    title: "Set Apart & Chosen",
    content: "27th Aniversay of Hope of Glory Christian Church.  A day to rediscover your calling.",
    date: "November 26, 2023",
    mediaID: "341440915275838",
    type: "video"
},
{
    id: 4,
    title: "Christians Engaged | Day 02",
    content: "Christians Engaged Day 2 live streaming.",
    date: "April 12, 2022",
    mediaID: "450797956803300",
    type: "video"
},
]

export const books = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",
  ];
